name: Deploy on Heroku. Naked Ruby

on:
  push:
    branches: [development]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.2.6
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "naked-ruby-blog" #Must be unique in Heroku
        heroku_email: ${{secrets.YOUR_EMAIL}}
        branch: "dev"
